### PR TITLE
Remove react-hot-loader from Babel preset

### PR DESCRIPTION
**Pull request by js62789**

### CODE REVIEW

**Comment by djMax** [comment]
I don't love this one. babel-preset-gasbuddy, though it supports use in react, doesn't require it. And peer deps kind of suck in general. What's the goal?

**Comment by js62789** [comment]
Yea after thinking about this one some more, I think we need to remove the react-hot-loader from our babel configuration entirely. a) A lot of our projects don't use React at all and b) hot reloading is enabled by applications with code like this
```javascript
if (process.env.NODE_ENV !== 'production') {
  router = hot(module)(Router);
}
```
If the application is responsible for enabling hot reloading, then I think the application should also be responsible for adding `react-hot-loader/babel` into its own Babel configuration like so
```javascript
{
  presets: ['gasbuddy'],
  plugins: ['react-hot-loader/babel']
}
```

**Comment by djMax** [comment]
Needs update

**Comment by djMax** [comment]
Going to just redo it in the other PR.

**Pull request closed without merging**
